language: go
go:
  - 1.7
env: "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/kintone/go-kintone
  - go get github.com/howeyc/gopass
  - go get golang.org/x/text/encoding
  - go get github.com/mitchellh/gox
script:
  - go vet -x ./...
  - gox -osarch="linux/amd64" -output build/linux-x64/cli-kintone
  - zip linux-x64.zip build/linux-x64/cli-kintone
  - gox -osarch="darwin/amd64" -output build/macos-x64/cli-kintone
  - zip macos-x64.zip build/macos-x64/cli-kintone
  - gox -osarch="windows/amd64" -output build/windows-x64/cli-kintone
  - zip windows-x64.zip build/windows-x64/cli-kintone.exe
  - gox -osarch="windows/386" -output build/windows/cli-kintone
  - zip windows.zip build/windows/cli-kintone.exe
deploy:
  provider: releases
  api_key:
    secure: "afx+IMehyPIxDMG+5CfE5vOo4QwIo3qHJ4RdF7ziUxpUpVFBGE+j3qT5aDLZbqMriOHdCnj6wps49wUveEQ6tldm5o266RUAtJmKIqzuhZ2E9qMyo4TQgFKYVg+qzc2weUSRCNJHx/eum5rRz7cLel78HKqY0AbMkoz6tYJLj0ERX96H/LCGLFoM5rvzWsDSIeZPhjjLsyzHM/Z5dCVc1lZtI96+2B/+iq1Ac9qkEHCQbiV3lL9XDboklLIZ3v5EkMmDw4ZBa4jziCq7SE2Topt3tGEJKh/Mt82NUuFhELkWiIII0AEg3WMAQkybPjJttqegkAGNBffDV08x155V1ab1ONvDKWS6x8vEBgsL7JF6ekcWqEie3pT2HYc1k7K8DjHfhPIAosYov5F5Esr5/ZlvQvDmfY6NxGuAp16PSjT0qaLEWGQptUfU/G4sRRUEtuIcEfwNHvKSX1XLOV2aIV62J5xXV+LFIWrXCiWmNsC2iZCwN6QLYhp3oiR0LQfTAJlclJeif7Qm+ue3L+r8tfoC44SdID3rd/Mq/XV4HAffgmnhLRwKX8H4SNa28Ww7/OCp5cV/7O8g1n5NNZIwv1+MD6VakGR1pTwFyLc5aDNAqvdPCfPFRLN16uHjPgNUwj4Ev/M6M6BH13z/q/MIL2thjBZBErNDO8wnL2wBe1Q="
  file:
    - "linux-x64.zip"
    - "macos-x64.zip"
    - "windows-x64.zip"
    - "windows.zip"
  skip_cleanup: true
  all_branches: true  # https://github.com/travis-ci/travis-ci/issues/1675
  on:
    tags: true
