language: go
go:
  - 1.13.7
env: "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mattn/gom
script:
  - go vet -x ./...
  # Install dependencies via gom
  - $HOME/gopath/bin/gom -production install

  # Build linux/amd64 archive
  - export GOOS="linux"
  - export GOARCH="amd64"
  - gom build -v -tags "forceposix" -o build/linux-x64/cli-kintone
  - zip linux-x64.zip build/linux-x64/cli-kintone

  # Build darwin/amd64 archive
  - export GOOS="darwin"
  - export GOARCH="amd64"
  - gom build -v -tags "forceposix" -o build/macos-x64/cli-kintone
  - zip macos-x64.zip build/macos-x64/cli-kintone

  # Build windows/amd64 archive
  - export GOOS="windows"
  - export GOARCH="amd64"
  - gom build -v -tags "forceposix" -o build/windows-x64/cli-kintone.exe
  - zip windows-x64.zip build/windows-x64/cli-kintone.exe

deploy:
  provider: releases
  api_key: 
    secure: "dqDCpfv4IUWH8lq9KknNkrKp1f4/ETqnFmY/EsJTvtgWCqBj5ZziEvLqEFbbokj/HFn19ZhZJa8emVQJyFYWkPE5x+S8VZraWH5mDJrMtto0ujAzR+dOyq5fydgvLSDNh2tflPHR4dD3gecvFq8mso98CNz/NWJfyxMPwVQ+bEcg1ghMsBFLIzZ95GFI/0dd1Vl01T/4DfD9LnaUdz/T8UCqf7ho0uWGiBswvmuDMm8USngj2DHdE5hWppn7gYevAhmUfil4/D4QEKd4Brz8P6qpzrxcOW9vSUF0ElV1+fA27cDEjUByTsO8wNrk2e9am9N2VOBErXAOhIP2qttGGaD/076sJoFkoHRez7kUp7lfmlOfUkoqxnwhNXQWkEgy6J7WrkCG6uFPXNtRpgEKPEf3zgcrkvWEfe2fb9651I3UpOmA3v8lPpg8YrQ9ozIndURVvgRTXZvXqzdntor3LiREbJHIVC974St7m6Plkt6DNKFfo6UKm6EvfaXsM+s1mkr3VO6TFTwnDcypSInf9G4nhphJwz/WWoFlaXp79y2e/pUMOSH5GXav0nEgmalngphYlUcHVXXVzyJJG+zR5sO5xdaQtHMRJkyvy3AT4dTvDhyN0PqDacZXiMqoF+3ZZiY6zABzepdshR9cYyxGXTbsq17kSybKmj1nzeNZW3Q="
  file:
    - "linux-x64.zip"
    - "macos-x64.zip"
    - "windows-x64.zip"
  skip_cleanup: true
  all_branches: true  # https://github.com/travis-ci/travis-ci/issues/1675
  on:
    tags: true
